name: Teste das funções do Sistema Escolar

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Configurar Node.JS
        uses: actions/setup-nodev4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test 